# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Doing the full EM Algorithm
#' 
#' @param y A vector of values for each observation
#' @param x The Numeric Matrix of X values for the models
#' @param weights The vector of weights for each model
#' @param sd Standard deviation
#' @param tolerance The level of chnage between iterations where the model will stop
#' 
#' @useDynLib ps6EBMA
#' 
#' @export
fullEM <- function(x, y, weights, sd, tolerance) {
    .Call('_ps6EBMA_fullEM', PACKAGE = 'ps6EBMA', x, y, weights, sd, tolerance)
}

#' Solving Equation 3 of the EM algorithm by computing our weights
#' 
#' @param z The matrix of prodicted z values
#' 
#' @useDynLib ps6EBMA
#' 
#' @export
w_hat <- function(z) {
    .Call('_ps6EBMA_w_hat', PACKAGE = 'ps6EBMA', z)
}

#' Solving Equation 2 of the EM Algorithm for Z_Hat
#' 
#' @param y A vector of values for each observation
#' @param x The Numeric Matrix of X values for the models
#' @param weights The vector of weights for each model
#' @param sd Standard deviation
#' 
#' @useDynLib ps6EBMA
#' 
#' @export
z_hat <- function(x, y, weights, sd) {
    .Call('_ps6EBMA_z_hat', PACKAGE = 'ps6EBMA', x, y, weights, sd)
}

